server:
  port: 8000
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=MYSQL;
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true # sql 로그 줄바꿈
  output:
    ansi:
      enabled: always

logging:
  level:
    org.hibernate.type: trace
    '[site.metacoding.finals]': DEBUG




filedir: "C://temp/image/"
