#oauth google, kakao
#인증 정보 파일화해서 .gitignore에 등록 처리해야 함!
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 52787272493-p0sac3659atd7kdj8h0ffjjp46aur2te.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
          kakao:
            client-id: 
            client-secret: 
            scope:
            - profile_nickname
            client-name: kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8000/login/oauth2/code/final
            client-authentication-method: POST
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id 